### ISSUE TITLE
I have a problem using Tab.get_cookies ().

### ISSUE THREAD

**Issue by litttley** [atroche/rust-headless-chrome#163] opened 2019-08-22 00:56 UTC
I have a problem using Tab.get_cookies (). when I set headless to flase ` let options = LaunchOptionsBuilder::default().headless(flase) .build()?`   Tab.get_cookies () is work well, but when I set headless to true 'let options = LaunchOptionsBuilder::default().headless(true) .build()?', I can only get some cookies after logging on to the website.here is the result

**.headless(false) work well!** 

`"cna=GtHkFdrzSyoCAT0cGBv3gxIV;"
"cookie2=163f252709b31945aaf7975a53a9adc2;"
"_tb_token_=5ee9ae73553e;"
"t=9a29ac3e4911c7a0ba96697b71da794e;"
"v=0;"
"uc1=cookie21=WqG3DMC9Edo1SB5NB6Qtng%3D%3D&existShop=true&lng=zh_CN&cookie15=UIHiLt3xD8xYTw%3D%3D&tag=8&cookie16=V32FPkk%2FxXMk5UvIbNtImtMfJQ%3D%3D&pas=0&cookie14=UoTaHo8NF71dwQ%3D%3D;"
"unb=675916252;"
"uc3=vt3=F8dBy3MPS5awfFKtrO8%3D&id2=VWhejXyLENU2&nk2=hngQ6eDTLEOX&lg2=UtASsssmOIJ0bQ%3D%3D;"
"csg=634f678a;"
"lgc=%5Cu900D%5Cu9065%5Cu5251125;"
"uc4=id4=0%40V8nWzgcNepr1kheE%2F28sDz38GbM%3D&nk4=0%40hLLVVFOcKX%2Fai7f%2Fz9ln5qJKyig%3D;"
"cookie17=VWhejXyLENU2;"
"dnk=%5Cu900D%5Cu9065%5Cu5251125;"
"skt=51d1663291ecc078;"
"existShop=MTU2NjQzNDEwMQ%3D%3D;"
"tracknick=%5Cu900D%5Cu9065%5Cu5251125;"
"_cc_=UIHiLt3xSw%3D%3D;"
"tg=0;"
"_l_g_=Ug%3D%3D;"
"sg=525;"
"_nk_=%5Cu900D%5Cu9065%5Cu5251125;"
"cookie1=UNk3ADZ3ewD6mCbtHBQ1MiNnZ5Bo8w4zd8Vw5%2FnZiCg%3D;"
"_mw_us_time_=1566434101819;"
"isg=BF1daFj33KHoa7iNbMst80vGbDmX0pCnD9wWNB8imbTj1n0I58qhnCvHBIr1EamE;"
"l=cBEJG3mHquhWtPupBOCN5uI8LG7OSIRA_uPRwCqXi_5B96T_KIbOkJ_FWF96VjWdO_YB4h6Mygv9-etuwICxnJSpXUJ1.;"`

**.headless(true) not well**
`"cna=GNLkFcclQ08CAT0cGBvk0SH6;"
"cookie2=140df401400b226dd2d595bbe5d8d81e;"
"_lastvisited=GNLkFcclQ08CAT0cGBvk0SH6%2C%2CGNLkFcclQ08CAT0cGBvk0SH6yLAVByod%2Cjzlyk02n%2Cjzlyk02n%2C1%2C2f7fcf30%2CGNLkFcclQ08CAT0cGBvk0SH6%2Cjzlyk02o;"
"l=cBQ1pf5rquh88RzbBOCahurza77OSCOYYuPzaNbMi_5In6T_I2bOkJ_15F96VjXd_W8Bqh6Mygv9-etkZe5Uy5IpXUJ1.;"
"_tb_token_=f9bb131076b53;"
"t=c15eb2fc96b5f41d014f04474a4ebf9e;"
"_umdata=G65502C96D32655CDBAB12878C5E7F12EF06E99;"
"isg=BFVVgDKmpMmngoC1o7Jf-QHyb1HP-ggPR3QOLNf6EUwbLnUgn6IZNGPs_HM9NSEc;"
"_uab_collina=156643432795075241426225;"
"v=0;"
"_uab_collina=156643432946225679932937;"`

**Comment by atroche** [comment] 2019-08-22 01:00
Interesting! So some of the cookies aren't being set in headless mode? Any chance you'd share your code so I can try to reproduce? Or tell me what the website is so I can try it?

Also, what OS and Chrome version are you using?

Thanks for the report.

**Comment by litttley** [comment] 2019-08-22 01:12
can you give me an email, I will send you an email, because there is my account information in the code

**Comment by atroche** [comment] 2019-08-22 01:12
sure, `alistair@sunburnt.country`.

**Comment by litttley** [comment] 2019-08-22 01:26
I have sent an email to you, I am using windows os

**Comment by atroche** [comment] 2019-08-22 04:41
Closing because it seems like the issue isn't to do with `tab.get_cookies()`.

**Closed by atroche** 2019-08-22 04:41 UTC
Labels: question
